{{ config(materialized='table') }}

with source_covid_data as (
    select * from {{ ref('snowflake_covid__covid_indonesia') }}
),

final as (
    select * from source_covid_data
    where LOCATION_LEVEL = 'Province'
)

select CAST(DATE AS date) as DATE, PROVINCE, LOCATION_ISO_CODE, LATITUDE, LONGITUDE, 
TOTAL_CASES, TOTAL_DEATHS, TOTAL_RECOVERED, TOTAL_ACTIVE_CASES,
NEW_CASES, NEW_DEATHS, NEW_RECOVERED, NEW_ACTIVE_CASES,
TOTAL_CASES_PER_MILLION, TOTAL_DEATHS_PER_MILLION,
NEW_CASES_PER_MILLION, NEW_DEATHS_PER_MILLION,
CASE_FATALITY_RATE, CASE_RECOVERED_RATE, 
GROWTH_FACTOR_OF_NEW_CASES, GROWTH_FACTOR_OF_NEW_DEATHS,
POPULATION

from final
order by DATE desc, 
TOTAL_CASES desc, TOTAL_DEATHS  desc, TOTAL_RECOVERED desc, TOTAL_ACTIVE_CASES desc,
NEW_CASES desc, NEW_DEATHS desc, NEW_RECOVERED desc, NEW_ACTIVE_CASES desc,
TOTAL_CASES_PER_MILLION desc, TOTAL_DEATHS_PER_MILLION desc, 
PROVINCE asc


-- select DATE, PROVINCE, TOTAL_DEATHS_PER_MILLION from final
-- order by TOTAL_DEATHS_PER_MILLION desc